config/routes.rb
Blog::Application.routes.draw do
  devise_for :users
  

  resources :categories
  
  resources :posts do
    resources :comments
  end

  namespace :admin do
    resources :posts do
      resources :comments
    end
    resources :categories
    get '/' => "admin#index"
  end

  root 'posts#index'

  

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
	validates :category, presence: true,
                    length: { minimum: 1 }
    attr_accessible :category
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  	belongs_to :post
  	validates :commenter, presence: true,
                    length: { minimum: 1 }
  	validates :body, presence: true,
                    length: { minimum: 1 }
    attr_accessible :commenter, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :user, :foreign_key => :author_id
	has_many :comments, dependent: :destroy
    attr_accessible :title, :text, :category_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, :foreign_key => :author_id

  attr_accessible :email, :password, :password_confirmation
  
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < AdminController
  def index
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController

	def new
    @category = Category.new
  end

	def index
    @categories = Category.all
    @category = Category.new
  end

  def show
  	@category = Category.find(params[:id])
	end

  def create
  	@category = Category.new(category_params)
 
  	@category.save
  	redirect_to admin_categories_path
	end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to admin_categories_path
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(params[:category].permit(:category))
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end

  private
  	
  def category_params
    params.require(:category).permit(:category)
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < AdminController

 
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params[:comment].permit(:commenter, :body))
    @comment.post =@post
    if @comment.save
      redirect_to admin_post_path(@post)
    else
      render 'admin/posts/show'
    end
  end
 
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to admin_post_path(@post)
  end
 
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController

  require 'CreatePostService'

  def new
    @post = Post.new
  end

  def index
    @posts = Post.all
  end
 
  def create
    author = current_user
    @post = Post.new(params[:post].permit(:title,:text,:category_id))
    begin
      create_post_service.process(@post, author, params[:post])
      flash[:notice] = "Create new post success"
      redirect_to admin_post_path(@post)
    rescue CreatePostService::EmptyTitleError
      flash[:notice] =  "Error: empty title"
      render 'admin/posts/new'
    rescue CreatePostService::EmptyPostError
      flash[:notice] =  "Error: empty post"
      render 'admin/posts/new'
    rescue CreatePostService::NoCategoryError
      flash[:notice] = "Please select the category."
      render 'admin/posts/new'
    rescue CreatePostService::PostError
      flash[:notice] = "Failed to save post"
      render 'admin/posts/new'
    end
  end
 
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :text, :category_id))
      redirect_to admin_post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
 
    redirect_to admin_posts_path
  end

	private
  def post_params
    params.require(:post).permit(:title, :text, :category_id)
  end

  def create_post_service
    CreatePostService.new()
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :check_admin

  private
  def check_admin
    if !user_signed_in?
      redirect_to new_user_session_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :load_categories



  private

  def load_categories
    @categories = Category.all
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
    @categories = Category.all
    @category = Category.new
  end

  def show
  	@category = Category.find(params[:id])
	end

  private
  	
  def category_params
    params.require(:category).permit(:category)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params[:comment].permit(:commenter, :body))
    @comment.post =@post
    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

	private
  def post_params
    params.require(:post).permit(:title, :text, :category_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/admin/index.html.erb
<h1>ADMIN PANEL</h1>

<h2>Things to manage</h2>

<p><%= link_to 'Posts', admin_posts_path %></p>
<p><%= link_to 'Categories', admin_categories_path %></p>
<br><br>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>Listing categories</h1>

<table>
	<% @categories.each do |category| %>
	<tr>
		<th>Name</th>
    	<td><%= category.category %></td>
    	 <td><%= link_to 'Edit', edit_admin_category_path(category) %></td>
    	<td><%= link_to 'Destroy', admin_category_path(category),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
	<% end %>
</table>

<h1>New category</h1>

<%= render 'form' %>

app/views/admin/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>

  <%= link_to 'Destroy Comment', [:admin, comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/admin/comments/_form.html.erb
<%= form_for([:admin, @post, @comment]) do |f| %>

  <% if @comment.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label "Text" %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>
<% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= select 'post', 'category_id', 
    Category.find(:all).collect {|c| [c.category, c.id]}, 
    :prompt => "Select a Category" %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Edit Post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Text</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.user.email.split("@").first %></td>
    <td><%= post.text %></td>
    <td><% if post.category %>
    <%= post.category.category %>
    <% else %>
    NO CATEGORY
    <% end %>
    </td>
    <td><%= link_to 'Show', admin_post_path(post) %></td>
    <td><%= link_to 'Edit', edit_admin_post_path(post) %></td>
    <td><%= link_to 'Destroy', admin_post_path(post),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<br>
<br>
<%= link_to 'Add new post', new_admin_post_path %>

app/views/admin/posts/new.html.erb
<h1>New post</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/show.html.erb
<article class="row">

    <div class="column_9 margin-bottom">
        <h2><%= link_to @post.title, post_path(@post), :class=> "text bold color theme" %></h2>
        <h5>
            <% if @post.category %>
            Category: 
            <%= @post.category.category %>
            <% end %> 
            Written by <a href="#" class="text bold color theme"><%= @post.user.email.split("@").first %></a> 
            <%= time_ago_in_words(@post.created_at) %> 
            ago
        </h5>
    </div>
    <p class="column_9">
        <%= @post.text %>
    </p>
</article>
<hr/>
 
<h2>Comments</h2>
<table>
  <tr>
    <th>Commenter</th>
    <th>Text</th>
    <th></th>
  </tr>
<% @post.comments.each do |comment| %>
  <tr>
    <td><%= comment.commenter %></td>
    <td><%= comment.body %></td>
    <td><%= link_to 'Destroy', [:admin, comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
 
<h2>Add a comment:</h2>
<%= render "admin/comments/form" %>
 
<%= link_to 'Edit Post', edit_admin_post_path(@post) %> |
<%= link_to 'Back to Posts', admin_posts_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
	<% @categories.each do |category| %>
	<tr>
		<th>Name</th>
    	<td><%= category.category %></td>
    </tr>
	<% end %>
</table>


<%= link_to 'Back to Posts', posts_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 

app/views/comments/_form.html.erb
<%= form_for([@post, @comment]) do |f| %>

  <% if @comment.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :commenter %><br />
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label "Text" %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>My Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
    <style>
        body > header .logo {
            margin-top: 8px;
            margin-right: 8px;
            max-height: 30px; }

        body > footer img {
            height: 18px;
            position: relative;
            top: 5px;
            left: 2px; }

        div.img.avatar {
            height: 46px;
            width: 46px;
            float: left;
            margin: 1%; }
    </style>
</head>

<body class="text thin">
<p class="navbar-text pull-right">

    <header class="bck light padding">
        <div class="row">
            <div class="column_6">
                <h2 class="text italic thin"><%= link_to 'My Blog', root_path %></h2>
            </div>
            <nav class="column_6  text right bold">
                <% if user_signed_in? %>
                    <strong><%= current_user.email %></strong>
                    <%= link_to "Admin panel", admin_path, :class => 'button tiny' %> 
                    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'button tiny' %> 
                    <a href="<%= destroy_user_session_path %>" data-method="delete" rel="nofollow" class="button tiny secondary alert" class = 'button small alert' > <span class="icon off"></span>Logout </a>
                <% else %>
                    <a href="<%= new_user_session_path %>" class="button secondary"  ><span class='icon user'></span> Login</a>
                    <a href="<%= new_user_registration_path %>" class="button" ><span class="icon pencil"></span>Sign up</a>
                <% end %>
            </nav>
        </div>
    </header>

    <section class="padding">
        <div class="row">
            <%if notice %>
                <div class="column_9 radius bck padding-top padding-bottom margin-bottom center text">
                <%= notice %>
                </div>
            <% end %>
        
            <%if alert %>
                <div class="column_9 alert radius bck padding-top padding-bottom margin-bottom center text">
                <%= alert %>
                </div>
            <% end %>

            <div class="column_9">
                <%= yield %>
            </div>

            <aside class="column_3">
                <h5 class="text normal">Categories</h5>
                <nav class="margin-bottom">
                    <% @categories.each do |category| %>
                        <a href="#" class="display block color theme"><%= category.category %></a>
                    <% end %>
                </nav>
            </aside>
        </div>
    </section>

    <footer class="bck dark padding">
        <div class="row margin-top margin-bottom">
            <div class="column_5">
                
            </div>
        </div>
    </footer>

    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="../package/tuktuk.js"></script>
</body>

</html>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<article class="row">

  <div class="column_9 margin-bottom">
    <h2><%= link_to post.title, post_path(post), :class=> "text bold color theme" %></h2>
     <h5>         
      <% if post.category %>
      Category: 
      <%= post.category.category %>
      <% end %> 
      Written by <a href="#" class="text bold color theme"><%= post.user.email.split("@").first %></a> 
      <%= time_ago_in_words(post.created_at) %> 
      ago
    </h5>
  </div>
  <p class="column_9">
    <%= post.text %>
  </p>
</article>
<hr/>
<% end %>

app/views/posts/show.html.erb
<article class="row">

  <div class="column_9 margin-bottom">
    <h2><%= link_to @post.title, post_path(@post), :class=> "text bold color theme" %></h2>
    <h5>
        <% if @post.category %>
        Category: 
        <%= @post.category.category %>
        <% end %> 
        Written by <a href="#" class="text bold color theme"><%= @post.user.email.split("@").first %></a> 
        <%= time_ago_in_words(@post.created_at) %> 
        ago
    </h5>
  </div>
  <p class="column_9">
    <%= @post.text %>
  </p>
</article>
<hr/>
<h2>Comments</h2>
<table>
  <tr>
    <th>Commenter</th>
    <th>Text</th>
  </tr>
<% @post.comments.each do |comment| %>
  <tr>
    <td><%= comment.commenter %></td>
    <td><%= comment.body %></td>
  </tr>
<% end %>
</table>
 
<h2>Add a comment:</h2>
<%= render "comments/form" %>
 
<%= link_to 'Back to Posts', posts_path %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= link_to "My Blog", controller: "posts" %>